version: '3.8'

services:
  api:
    build:
      context: ../../
      dockerfile: infrastructure/docker/Dockerfile.api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgresql://dukaan:dukaanpass@postgres:5432/dukaanpilot
      - JWT_SECRET=dukaanpilot-secret-dev
    depends_on:
      - postgres

  web:
    build:
      context: ../../
      dockerfile: infrastructure/docker/Dockerfile.web
    ports:
      - "3000:80"
    depends_on:
      - api

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dukaan
      - POSTGRES_PASSWORD=dukaanpass
      - POSTGRES_DB=dukaanpilot
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
